output_dir: outputs/geouni-512x512-0130-t2i-mmu-debug/gen_images
model:
    vq_model:
        type: "geo"
        vq_model_config: 
            double_z: False
            z_channels: 13
            resolution: 512
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [1,2,2,2,4,4]   # num_down = len(ch_mult)-1
            num_res_blocks: 4
        pretrained_model_path: "/lustre/home/2201210053/GEOMETERY/OpenMagVit-CKPT/expr_1120_mask_down32_z13/ckpt/epoch=184-step=68820.ckpt"

    geouni:
        load_from_geouni: false
        pretrained_model_path: "outputs/geouni-512x512-0130-t2i-mmu-debug/checkpoint-1000/unwrapped_model"
        vocab_size: 159866
        llm_vocab_size: 151665
        llm_model_path: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B' # 'Qwen/Qwen2.5-Math-1.5B'
        codebook_size: 8192
        num_vq_tokens: 256
        num_new_special_tokens: 9  # <|soi|> <|eoi|> <|t2i|> <|formalization|> <|reasoning|> <|mix|> <answer> </answer> [PAD]

dataset:   
    params:
        validation_prompts_file: null
    preprocessing:
        max_seq_length: 800
        resolution: 512
