wandb:
  entity: null
#  run_id: askkz9i2
  resume: 'auto'

experiment:
    project: "training"
    name: "geouni-512x512-0120"
    output_dir: "outputs/geouni-512x512-0120"
    save_every: 500
    generate_every: 500
    log_every: 50
    log_grad_norm_every: 500
    checkpoints_total_limit: 1
    resume_from_checkpoint: null # 'latest'

model:
    vq_model:
        type: "geo"
        vq_model_config: 
            double_z: False
            z_channels: 13
            resolution: 512
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [1,2,2,2,4,4]  # num_down = len(ch_mult)-1
            num_res_blocks: 4
        pretrained_model_path: "/lustre/home/2001110054/GEO-Open-MAGVIT2/outputs/expr_1120_mask_down32_z13/ckpt/epoch=184-step=68820.ckpt"

        
    geouni:
        load_from_geouni: false
        pretrained_model_path: null
        vocab_size: 159864
        llm_vocab_size: 151665
        llm_model_path: 'Qwen/Qwen2.5-0.5B'
        codebook_size: 8192
        num_vq_tokens: 256
        num_new_special_tokens: 7 # <|soi|>, <|eoi|>, <|t2i|>, <|mmu|>, <|mix|>, <|sot|>, [PAD]

dataset:
    gen_type: "t2i"
    und_type: "captioning"
    combined_loader_mode: "max_size_cycle"
    params:
        t2i_image_folder: data/formalgeo7k/formalgeo7k_v2
        t2i_json_path: data/formalgeo7k/formalgeo7k_v2/custom_json/t2i/train.json
        validation_prompts_file: "validation_prompts/geoprompts_test.txt"
        shuffle_buffer_size: 1000
        num_workers: 16
        resolution: 512
        pin_memory: True
        persistent_workers: True

    preprocessing:
        max_seq_length: 384 # for text tokens
        resolution: 512

optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 5e-5
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.01
        epsilon: 1e-8

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 200

training:
    gradient_accumulation_steps: 1
    batch_size_t2i: 8
    num_train_epochs: 10000000
    mixed_precision: "bf16"
    enable_tf32: True
    seed: 10086
    max_train_steps: 50000 # to be determined according to the scale of high-quality dataset
    max_grad_norm: null
    t2i_coeff: 1.0
    lm_coeff: 0.1
    mmu_coeff: 1.0