wandb:
  entity: null
#  run_id: askkz9i2
  resume: 'auto'

experiment:
    project: "training"
    name: "show-o-finetuning-512x512-T2I_0109-overfit-FormalLanguage-32Down-AutoReg"
    output_dir: "outputs/show-o-finetuning-512x512-0109-overfit-T2I-FormalLanguage-32Down-AutoReg"
    save_every: 1000
    eval_every: 1000
    generate_every: 500
    log_every: 50
    log_grad_norm_every: 500
    resume_from_checkpoint: 'latest' # 'latest'
    checkpoints_total_limit: 1

model:
    vq_model:
        type: "geo"
        vq_model_config: 
            double_z: False
            z_channels: 13
            resolution: 512
            in_channels: 3
            out_ch: 3
            ch: 128
            ch_mult: [1,2,2,2,4,4]  # num_down = len(ch_mult)-1
            num_res_blocks: 4
        pretrained_model_path: "/lustre/home/2001110054/GEO-Open-MAGVIT2/outputs/expr_1120_mask_down32_z13/ckpt/epoch=184-step=68820.ckpt"

        
    showo:
        load_from_showo: True
        pretrained_model_path: "showlab/show-o-512x512"
        w_clip_vit: False
        vocab_size: 58498
        llm_vocab_size: 50295
        llm_model_path: 'microsoft/phi-1_5'
        codebook_size: 8192
        num_vq_tokens: 256
        num_new_special_tokens: 10  # <|soi|> <|eoi|> <|sov|> <|eov|> <|t2i|> <|mmu|> <|t2v|> <|v2v|> <|lvg|> <|pad|>

    # gradient_checkpointing: True

dataset:
    gen_type: "t2i"
    und_type: "captioning"
    combined_loader_mode: "max_size_cycle"
    params:
        t2i_image_folder: data/formalgeo7k/formalgeo7k_v2
        t2i_json_path: data/formalgeo7k/formalgeo7k_v2/custom_json/t2i_overfit/train.json
        validation_prompts_file: "validation_prompts/geoprompts_test.txt"
        shuffle_buffer_size: 1000
        num_workers: 8
        resolution: 512
        pin_memory: True
        persistent_workers: True

    preprocessing:
        max_seq_length: 256 # for text tokens
        resolution: 512

optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 1e-5
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.01
        epsilon: 1e-8

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 1000

training:
    gradient_accumulation_steps: 1
    noise_type: "mask"
    batch_size_t2i: 8
    num_train_epochs: 30000000
    mixed_precision: "bf16"
    enable_tf32: True
    seed: 111
    max_train_steps: 100000 # to be determined according to the scale of high-quality dataset
    overfit_one_batch: False
    cond_dropout_prob: 0.0
    min_masking_rate: 0.0
    label_smoothing: 0.0
    max_grad_norm: null
    guidance_scale: 0.0
    generation_timesteps: 12
    t2i_coeff: 1.0
    lm_coeff: 0.1
    mmu_coeff: 1.0